name: test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  planner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        tf_version: "1.0.0" 

    - name: Terraform Init
      run: terraform init    
      
    - name: Terraform validate
      run: terraform validate


